# Generated by Django 6.0.4 on 2026-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default='', max_length=6, unique=True, verbose_name='Код подтверждения'),
            preserve_default=False,
        ),
    ]
