# Generated by Django 6.0.4 on 2026-04-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
