# Generated by Django 6.0.4 on 2026-04-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCompany',
        ),
    ]
